version: '3.8'
services:
  backend:
    image: vietentertainment2023/ve-backend:1.3.0
    depends_on:
      - db
      - keycloak
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PWD=postgres
    ports:
      - 8888:8888
    networks:
      - internal-network
    restart: on-failure:10
  db:
    image: postgis/postgis:14-3.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal-network
  keycloak:
    image: vietentertainment2023/ve-keycloak:1.1.0
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloakdb
      KC_DB: postgres
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_URL: http://keycloak:8080/auth
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev" ]
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - keycloak-db
    networks:
      - internal-network
  keycloak-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloakdb
    volumes:
      - keycloakdb:/var/lib/postgresql/data
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge

volumes:
  db:
    driver: local
  keycloakdb:
    driver: local
