version: '3.8'
services:
  backend:
    image: duckhai1/ve-backend:0.1.3
    depends_on:
      - db
      - keycloak
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PWD=postgres
    ports:
      - 8888:8888
    networks:
      - internal-network
    restart: on-failure:10
  db:
    image: postgis/postgis:14-3.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal-network
  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      DB_ADDR: keycloak-db
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_PORT: 5432
      DB_DATABASE: keycloakdb
      DB_VENDOR: postgres
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080/auth
    ports:
      - 8080:8080
    depends_on:
      - keycloak-db
    networks:
      - internal-network
  keycloak-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloakdb
    volumes:
      - keycloakdb:/var/lib/postgresql/data
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge

volumes:
  db:
    driver: local
  keycloakdb:
    driver: local
