package com.EntertainmentViet.backend.features.security.roles;

public enum AdminRole {
  ADMIN_BROWSE_ORGANIZER,
  ADMIN_APPROVE_ORGANIZER,
  ADMIN_UPDATE_ORGANIZER,
  ADMIN_DEACTIVE_ORGANIZER,
  ADMIN_REJECT_ORGANIZER,
  ADMIN_BROWSE_TALENT,
  ADMIN_APPROVE_TALENT,
  ADMIN_UPDATE_TALENT,
  ADMIN_DEACTIVE_TALENT,
  ADMIN_REJECT_TALENT,
  ADMIN_BROWSE_ADVERTISEMENT,
  ADMIN_APPROVE_ADVERTISEMENT,
  ADMIN_DELETE_ADVERTISEMENT,
  ADMIN_UPDATE_ADVERTISEMENT,
  ADMIN_BROWSE_BOOKING,
  ADMIN_UPDATE_BOOKING,
  ADMIN_READ_SCORE,
  ADMIN_UPDATE_SCORE
}
