package com.EntertainmentViet.backend.features.security.roles;

public enum BookingRole {
  READ_BOOKING,
  ADD_BOOKING,
  UPDATE_BOOKING,
  BROWSE_BOOKING_ORGANIZER,
  ACCEPT_BOOKING_ORGANIZER,
  CANCEL_BOOKING_ORGANIZER,
  BROWSE_BOOKING_TALENT,
  ACCEPT_BOOKING_TALENT,
  CANCEL_BOOKING_TALENT,
}
