spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PWD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: update  # TODO: update back to "validate" when finish making database schema
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

keycloak:
  realm: ve-sso
  resource: backend
  auth-server-url: http://localhost:18080/auth
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username
  use-resource-role-mappings: true

secret:
  clientSecret: Z6POqTB2rwUGXbEnWi6tGtBEVjuM1y3g
