spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://shielded-escarpment-36770.herokuapp.com/auth/realms/ve-sso