server:
  port: 8888
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PWD:postgres}
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  flyway:
    enabled: true
    outOfOrder: false
    locations:
      - classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/ve-sso
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_NULL_MAP_VALUES: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

hibernate:
  hbm2ddl:
    auto: validate

security:
  allowed_origins:
    - http://localhost:3000

authentication:
  keycloak:
    realm: ve-sso
    resource: backend
    serverUrl: http://keycloak:8080/auth
    adminUsername: ssoadmin
    adminPassword: ssoadmin  # TODO try to use keystore to hide this

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE