server:
  port: 8888
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PWD:postgres}
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        metadata_builder_contributor: com.EntertainmentViet.backend.config.db.SqlFunctionMetadataBuilderContributor
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  flyway:
    enabled: true
    outOfOrder: true
    locations:
      - classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/ve-sso
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_NULL_MAP_VALUES: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: no.reply.vietentertainment@gmail.com
    password: pkpiqstjhyhvrdfd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftlh


hibernate:
  hbm2ddl:
    auto: validate

security:
  allowed_origins:
    - http://localhost:3000
    - http://localhost:3005

authentication:
  keycloak:
    realm: ve-sso
    resource: backend
    serverUrl: http://keycloak:8080/auth
    adminUsername: ssoadmin
    adminPassword: ssoadmin  # TODO try to use keystore to hide this
    resetPasswordUrl: http://localhost:3000/reset-password

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

cloud:
  aws:
    region:
      static: ap-southeast-1
    stack:
      auto: false
    credentials:
      accessKey: AKIA5BNKYFTGKHR5ZOGH
      secretKey: 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


amazonProperties:
  bucketName: ve-storage

static-resource:
  default-avatar: a4805998-c1cc-4dc6-a34e-53012eef4b99_true_1674145514985.png

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE