spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.heartofshow.com/auth/realms/ve-sso

security:
  allowed_origins:
    - http://host.docker.internal:3000
    - http://host.docker.internal:3005
    - http://localhost:3000
    - http://localhost:3005
    - https://heartofshow.com/
    - https://api.heartofshow.com/
    - https://auth.heartofshow.com/
    - https://cms.heartofshow.com/

authentication:
  keycloak:
    serverUrl: https://auth.heartofshow.com/auth
    resetPasswordUrl: https://heartofshow.com/reset-password