spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.iambao.me/auth/realms/ve-sso

security:
  allowed_origins:
    - http://host.docker.internal:3000
    - http://localhost:3000

authentication:
  keycloak:
    serverUrl: https://auth.iambao.me/auth