spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/ve-sso

security:
  allowed_origins:
    - http://host.docker.internal:3000
    - http://host.docker.internal:3005

authentication:
  keycloak:
    serverUrl: http://keycloak:8080/auth
    resetPasswordUrl: http://localhost:3000/reset-password