version: '3.8'

services:
  keycloak-config-cli:
    build:
      context: .
      args:
        KEYCLOAK_CONFIG_CLI_VERSION: ${KEYCLOAK_CONFIG_CLI_VERSION?}
        KEYCLOAK_VERSION: ${KEYCLOAK_VERSION?}
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL?}
      - KEYCLOAK_USER=${KEYCLOAK_USER?}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD?}
      - ENVIRONMENT=${ENVIRONMENT?}
      - IMPORT_FILES_LOCATIONS=file:/realm-ve-sso.yaml
      - KEYCLOAK_AVAILABILITYCHECK_ENABLED=true
      - KEYCLOAK_AVAILABILITYCHECK_TIMEOUT=120s
      - IMPORT_VARSUBSTITUTION_ENABLED=true
      # Uncomment to enable debug output
      # - LOGGING_LEVEL_ROOT=debug
      # - LOGGING_LEVEL_KEYCLOAKCONFIGCLI=debug
