ALTER TABLE priority_score
    DROP CONSTRAINT FK_PRIORITYSCORE_ON_SCORE_TYPE,
    ADD CONSTRAINT FK_PRIORITYSCORE_ON_SCORE_TYPE FOREIGN KEY (score_type_id) REFERENCES score_type (id) ON UPDATE CASCADE ON DELETE CASCADE;

UPDATE score_type
SET uid = 'bd71244f-6949-4daa-a695-b3e05dd39bf6'
WHERE id = 1;

ALTER TABLE score_type
ALTER COLUMN uid SET NOT NULL;