ALTER TYPE booking_status ADD VALUE 'ORGANIZER_FINISH';
ALTER TYPE booking_status ADD VALUE 'TALENT_FINISH';

ALTER TABLE booking
ADD COLUMN is_review BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN extensions JSONB;