ALTER TABLE review
ADD COLUMN organizer_id BIGINT NOT NULL,
ADD COLUMN uid UUID NOT NULL;

ALTER TABLE review ADD CONSTRAINT FK_REVIEW_ON_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES organizer (id);
