ALTER TABLE event_open_position
ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE job_offer
ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE event
ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE package
ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;