{
  clientId: "backend",
  protocol: "openid-connect",
  enabled: true,
  redirectUris: [
      "$(properties:properties/$(env:ENVIRONMENT).properties::host)/*",
  ],
  webOrigins: [
      "+",
  ],
  standardFlowEnabled: true,
  directAccessGrantsEnabled: true,
  publicClient: false,
  clientAuthenticatorType: "client-secret",
  secret: "$(properties:properties/$(env:ENVIRONMENT).properties::client_secret)",
  attributes: {
    access.token.lifespan: 6
  }
},