{
  clientId: "backend",
  redirectUris: [
      "$(properties:properties/$(env:ENVIRONMENT).properties::host)/api/*",
  ],
  webOrigins: [
      "+",
  ],
  directAccessGrantsEnabled: true,
  publicClient: true,
},