"backend": [
  {
    "name": "VERIFY_ORGANIZER"
  },
  {
    "name": "READ_ORGANIZER"
  },
  {
    "name": "READ_ORGANIZER_CONFIDENTIAL"
  },
  {
    "name": "UPDATE_ORGANIZER"
  },
  {
    "name": "UPDATE_ORGANIZER_CONFIDENTIAL"
  },
  {
    "name": "RECEIVE_ORGANIZER_CASH"
  },
  {
    "name": "PAY_ORGANIZER_CASH"
  },
  {
    "name": "BROWSE_JOBOFFER"
  },
  {
    "name": "ADD_JOBOFFER"
  },
  {
    "name": "READ_JOBOFFER"
  },
  {
    "name": "UPDATE_JOBOFFER"
  },
  {
    "name": "DELETE_JOBOFFER"
  },
  {
    "name": "BROWSE_EVENT"
  },
  {
    "name": "ADD_EVENT"
  },
  {
    "name": "READ_EVENT"
  },
  {
    "name": "UPDATE_EVENT"
  },
  {
    "name": "DELETE_EVENT"
  },
  {
    "name": "BROWSE_EVENT_BOOKING"
  },
  {
    "name": "APPLY_ORGANIZER_POSITION"
  },
  {
    "name": "BROWSE_POSITION_APPLICANT"
  },
  {
    "name": "ACCEPT_POSITION_APPLICANT"
  },
  {
    "name": "REJECT_POSITION_APPLICANT"
  },
  {
    "name": "BROWSE_EVENT_POSITION"
  },
  {
    "name": "ADD_CART_ITEM"
  },
  {
    "name": "READ_CART_ITEM"
  },
  {
    "name": "UPDATE_CART_ITEM"
  },
  {
    "name": "DELETE_CART_ITEM"
  },
  {
    "name": "READ_SHOPPING_CART"
  },
  {
    "name": "CLEAR_SHOPPING_CART"
  },
  {
    "name": "ADD_EVENT_POSITION"
  },
  {
    "name": "READ_EVENT_POSITION"
  },
  {
    "name": "UPDATE_EVENT_POSITION"
  },
  {
    "name": "DELETE_EVENT_POSITION"
  },
  {
    "name": "BROWSE_TALENT"
  },
  {
    "name": "VERIFY_TALENT"
  },
  {
    "name": "READ_TALENT"
  },
  {
    "name": "READ_TALENT_CONFIDENTIAL"
  },
  {
    "name": "UPDATE_TALENT"
  },
  {
    "name": "UPDATE_TALENT_CONFIDENTIAL"
  },
  {
    "name": "RECEIVE_TALENT_CASH"
  },
  {
    "name": "PAY_TALENT_CASH"
  },
  {
    "name": "BROWSE_PACKAGE"
  },
  {
    "name": "ADD_PACKAGE"
  },
  {
    "name": "READ_PACKAGE"
  },
  {
    "name": "UPDATE_PACKAGE"
  },
  {
    "name": "DELETE_PACKAGE"
  },
  {
    "name": "ORDER_TALENT_PACKAGE"
  },
  {
    "name": "BROWSE_PACKAGE_ORDER"
  },
  {
    "name": "ACCEPT_PACKAGE_ORDER"
  },
  {
    "name": "REJECT_PACKAGE_ORDER"
  },
  {
    "name": "BROWSE_BOOKING_ORGANIZER"
  },
  {
    "name": "ACCEPT_BOOKING_ORGANIZER"
  },
  {
    "name": "CANCEL_BOOKING_ORGANIZER"
  },
  {
    "name": "FINISH_BOOKING_ORGANIZER"
  },
  {
    "name": "BROWSE_BOOKING_TALENT"
  },
  {
    "name": "ACCEPT_BOOKING_TALENT"
  },
  {
    "name": "CANCEL_BOOKING_TALENT"
  },
  {
    "name": "FINISH_BOOKING_TALENT"
  },
  {
    "name": "READ_BOOKING"
  },
  {
    "name": "ADD_BOOKING"
  },
  {
    "name": "UPDATE_BOOKING"
  },
  {
    "name": "BROWSE_ADVERTISEMENT"
  },
  {
    "name": "ADD_ADVERTISEMENT"
  },
  {
    "name": "READ_ADVERTISEMENT"
  },
  {
    "name": "UPDATE_ADVERTISEMENT"
  },
  {
    "name": "DELETE_ADVERTISEMENT"
  },
  {
    "name": "GET_ADVERTISEMENT_CASH"
  },
  {
    "name": "PAY_ADVERTISEMENT_CASH"
  },
  {
    "name": "BROWSE_TALENT_FEEDBACK"
  },
  {
    "name": "READ_TALENT_FEEDBACK"
  },
  {
    "name": "ADD_TALENT_FEEDBACK"
  },
  {
    "name": "BROWSE_ORGANIZER_FEEDBACK"
  },
  {
    "name": "READ_ORGANIZER_FEEDBACK"
  },
  {
    "name": "ADD_ORGANIZER_FEEDBACK"
  },
  {
    "name": "READ_REVIEW"
  },
  {
    "name": "ADD_REVIEW"
  },
  {
    "name": "ADMIN_BROWSE_ORGANIZER"
  },
  {
    "name": "ADMIN_READ_ORGANIZER"
  },
  {
    "name": "ADMIN_APPROVE_ORGANIZER"
  },
  {
    "name": "ADMIN_UPDATE_ORGANIZER"
  },
  {
    "name": "ADMIN_DEACTIVE_ORGANIZER"
  },
  {
    "name": "ADMIN_REJECT_ORGANIZER"
  },
  {
    "name": "ADMIN_BROWSE_TALENT"
  },
  {
    "name": "ADMIN_READ_TALENT"
  },
  {
    "name": "ADMIN_APPROVE_TALENT"
  },
  {
    "name": "ADMIN_UPDATE_TALENT"
  },
  {
    "name": "ADMIN_DEACTIVE_TALENT"
  },
  {
    "name": "ADMIN_REJECT_TALENT"
  },
  {
    "name": "ADMIN_BROWSE_ADVERTISEMENT"
  },
  {
    "name": "ADMIN_APPROVE_ADVERTISEMENT"
  },
  {
    "name": "ADMIN_DELETE_ADVERTISEMENT"
  },
  {
    "name": "ADMIN_UPDATE_ADVERTISEMENT"
  },
  {
    "name": "ADMIN_BROWSE_BOOKING"
  },
  {
    "name": "ADMIN_READ_BOOKING"
  },
  {
    "name": "ADMIN_UPDATE_BOOKING"
  },
  {
    "name": "ADMIN_UPDATE_BOOKING_PROOF"
  },
  {
    "name": "ADMIN_UPDATE_BOOKING_PAID"
  },
  {
    "name": "READ_CATEGORY"
  },
  {
    "name": "READ_LOCATION"
  },
  {
    "name": "READ_FILE"
  },
  {
    "name": "UPLOAD_FILE"
  },
  {
    "name": "DELETE_FILE"
  },
  {
    "name": "ROOT"
  },
  {
    "name": "READ_SCORE"
  },
  {
    "name": "UPDATE_SCORE"
  },
  {
    "name": "DELETE_SCORE"
  },
  {
    "name": "READ_CONFIG"
  },
  {
    "name": "CONFIG_FINANCE"
  },
  {
    "name": "READ_BOOKING_NOTI"
  },
  {
    "name": "UPDATE_BOOKING_NOTI"
  },
  {
    "name": "READ_USER_FEE"
  },
  {
    "name": "UPDATE_USER_FEE"
  }
]
