[
  {
    "name": "ORGANIZER_READ_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "READ_FILE",
          "VERIFY_ORGANIZER",
          "READ_ORGANIZER",
          "READ_ORGANIZER_CONFIDENTIAL",
          "BROWSE_JOBOFFER",
          "READ_JOBOFFER",
          "BROWSE_EVENT",
          "READ_EVENT",
          "BROWSE_POSITION_APPLICANT",
          "BROWSE_EVENT_POSITION",
          "READ_EVENT_POSITION",
          "BROWSE_BOOKING_ORGANIZER",
          "BROWSE_BOOKING_TALENT",
          "READ_BOOKING",
          "READ_CATEGORY",
          "READ_LOCATION",
          "BROWSE_TALENT",
          "READ_TALENT",
          "BROWSE_PACKAGE",
          "BROWSE_ORGANIZER_FEEDBACK",
          "READ_ORGANIZER_FEEDBACK",
          "READ_REVIEW",
          "READ_PACKAGE",
          "READ_SHOPPING_CART",
          "READ_CART_ITEM",
          "UPDATE_ORGANIZER_CONFIDENTIAL",
          "READ_SCORE",
          "BROWSE_EVENT_BOOKING"
        ]
      }
    }
  },
  {
    "name": "ORGANIZER_WRITE_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "UPLOAD_FILE",
          "ADD_JOBOFFER",
          "DELETE_JOBOFFER",
          "ADD_EVENT",
          "DELETE_EVENT",
          "ORDER_TALENT_PACKAGE",
          "ADD_BOOKING",
          "ADD_ORGANIZER_FEEDBACK",
          "ADD_EVENT_POSITION",
          "DELETE_EVENT_POSITION",
          "CLEAR_SHOPPING_CART",
          "ADD_CART_ITEM",
          "ADD_REVIEW",
          "DELETE_CART_ITEM",
        ]
      }
    }
  },
  {
    "name": "ORGANIZER_MODIFY_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "DELETE_FILE",
          "UPDATE_ORGANIZER",
          "UPDATE_JOBOFFER",
          "UPDATE_EVENT",
          "ACCEPT_POSITION_APPLICANT",
          "REJECT_POSITION_APPLICANT",
          "UPDATE_EVENT_POSITION",
          "ACCEPT_BOOKING_ORGANIZER",
          "CANCEL_BOOKING_ORGANIZER",
          "UPDATE_BOOKING",
          "UPDATE_CART_ITEM",
          "FINISH_BOOKING_ORGANIZER",
          "UPDATE_ORGANIZER_CONFIDENTIAL"
        ]
      }
    }
  },
  {
    "name": "ORGANIZER_PAYMENT_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "RECEIVE_ORGANIZER_CASH",
          "PAY_ORGANIZER_CASH"
        ]
      }
    }
  },
  {
    "name": "TALENT_READ_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "READ_FILE",
          "VERIFY_TALENT",
          "READ_TALENT",
          "READ_TALENT_CONFIDENTIAL",
          "BROWSE_PACKAGE",
          "READ_PACKAGE",
          "BROWSE_PACKAGE_ORDER",
          "BROWSE_BOOKING_TALENT",
          "BROWSE_BOOKING_ORGANIZER",
          "READ_BOOKING",
          "BROWSE_ADVERTISEMENT",
          "READ_ADVERTISEMENT",
          "READ_CATEGORY",
          "READ_LOCATION",
          "READ_ORGANIZER",
          "BROWSE_TALENT_FEEDBACK",
          "READ_TALENT_FEEDBACK",
          "READ_REVIEW",
          "BROWSE_EVENT_POSITION",
          "READ_EVENT_POSITION",
          "READ_EVENT",
          "BROWSE_EVENT",
          "UPDATE_TALENT_CONFIDENTIAL",
        ]
      }
    }
  },
  {
    "name": "TALENT_WRITE_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "UPLOAD_FILE",
          "APPLY_ORGANIZER_POSITION",
          "ADD_PACKAGE",
          "DELETE_PACKAGE",
          "ADD_BOOKING",
          "ADD_ADVERTISEMENT",
          "DELETE_ADVERTISEMENT",
          "ADD_TALENT_FEEDBACK",
        ]
      }
    }
  },
  {
    "name": "TALENT_MODIFY_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "DELETE_FILE",
          "UPDATE_TALENT",
          "UPDATE_TALENT_CONFIDENTIAL",
          "UPDATE_PACKAGE",
          "ACCEPT_PACKAGE_ORDER",
          "REJECT_PACKAGE_ORDER",
          "ACCEPT_BOOKING_TALENT",
          "CANCEL_BOOKING_TALENT",
          "UPDATE_BOOKING",
          "UPDATE_ADVERTISEMENT",
          "FINISH_BOOKING_TALENT"
        ]
      }
    }
  },
  {
    "name": "TALENT_PAYMENT_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "GET_ADVERTISEMENT_CASH",
          "PAY_ADVERTISEMENT_CASH",
          "RECEIVE_TALENT_CASH",
          "PAY_TALENT_CASH"
        ]
      }
    }
  },
  {
    "name": "ADMIN_READ_ORGANIZER_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "READ_ORGANIZER_CONFIDENTIAL",
          "ADMIN_BROWSE_ORGANIZER",
          "ADMIN_READ_ORGANIZER"
        ]
      }
    }
  },
  {
    "name": "ADMIN_RESOLVE_ORGANIZER_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "ADMIN_APPROVE_ORGANIZER",
          "ADMIN_UPDATE_ORGANIZER",
          "ADMIN_REJECT_ORGANIZER"
        ]
      }
    }
  },
  {
    "name": "ADMIN_ARCHIVE_ORGANIZER_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "ADMIN_DEACTIVE_ORGANIZER"
        ]
      }
    }
  },
  {
    "name": "ADMIN_READ_TALENT_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "READ_TALENT_CONFIDENTIAL",
          "ADMIN_BROWSE_TALENT",
          "ADMIN_BROWSE_ADVERTISEMENT",
          "READ_SCORE",
          "ADMIN_READ_TALENT",
        ]
      }
    }
  },
  {
    "name": "ADMIN_RESOLVE_TALENT_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "ADMIN_APPROVE_TALENT",
          "ADMIN_UPDATE_TALENT",
          "ADMIN_REJECT_TALENT",
          "ADMIN_APPROVE_ADVERTISEMENT",
          "ADMIN_UPDATE_ADVERTISEMENT",
          "UPDATE_SCORE",
        ]
      }
    }
  },
  {
    "name": "ADMIN_ARCHIVE_TALENT_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "ADMIN_DEACTIVE_TALENT",
          "ADMIN_DELETE_ADVERTISEMENT"
        ]
      }
    }
  },
  {
    "name": "ADMIN_READ_BOOKING_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "READ_FILE",
          "ADMIN_BROWSE_BOOKING",
          "ADMIN_READ_BOOKING"
        ]
      }
    }
  },
  {
    "name": "ADMIN_RESOLVE_BOOKING_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
          "UPLOAD_FILE",
          "DELETE_FILE",
          "ADMIN_UPDATE_BOOKING"
        ]
      }
    }
  }
]