[
  {
    "name": "ORGANIZER_READ_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "VERIFY_ORGANIZER",
            "SELF_READ_ORGANIZER",
            "BROWSE_JOBOFFER",
            "READ_JOBOFFER",
            "BROWSE_EVENT",
            "READ_EVENT",
            "BROWSE_EVENT_APPLICANT",
            "BROWSE_BOOKING_ORGANIZER",
            "READ_BOOKING",
            "READ_CATEGORY",
            "BROWSE_TALENT",
            "BROWSE_PACKAGE"
        ]
      }
    }
  },
  {
    "name": "ORGANIZER_WRITE_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "ADD_JOBOFFER",
            "DELETE_JOBOFFER",
            "ADD_EVENT",
            "DELETE_EVENT",
            "ORDER_TALENT_PACKAGE",
            "ADD_BOOKING"
        ]
      }
    }
  },
  {
    "name": "ORGANIZER_MODIFY_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "SELF_UPDATE_ORGANIZER",
            "UPDATE_JOBOFFER",
            "UPDATE_EVENT",
            "ACCEPT_EVENT_APPLICANT",
            "REJECT_EVENT_APPLICANT",
            "ACCEPT_BOOKING_ORGANIZER",
            "CANCEL_BOOKING_ORGANIZER",
            "UPDATE_BOOKING"
        ]
      }
    }
  },
  {
    "name": "ORGANIZER_PAYMENT_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "RECEIVE_ORGANIZER_CASH",
            "PAY_ORGANIZER_CASH"
        ]
      }
    }
  },
  {
    "name": "TALENT_READ_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "VERIFY_TALENT",
            "SELF_READ_TALENT",
            "BROWSE_PACKAGE",
            "READ_PACKAGE",
            "BROWSE_PACKAGE_ORDER",
            "BROWSE_BOOKING_TALENT",
            "READ_BOOKING",
            "BROWSE_ADVERTISEMENT",
            "READ_ADVERTISEMENT",
            "READ_CATEGORY"
        ]
      }
    }
  },
  {
    "name": "TALENT_WRITE_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "APPLY_ORGANIZER_EVENT",
            "ADD_PACKAGE",
            "DELETE_PACKAGE",
            "ADD_BOOKING",
            "ADD_ADVERTISEMENT",
            "DELETE_ADVERTISEMENT"
        ]
      }
    }
  },
  {
    "name": "TALENT_MODIFY_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "SELF_UPDATE_TALENT",
            "UPDATE_PACKAGE",
            "ACCEPT_PACKAGE_ORDER",
            "REJECT_PACKAGE_ORDER",
            "ACCEPT_BOOKING_TALENT",
            "CANCEL_BOOKING_TALENT",
            "UPDATE_BOOKING",
            "UPDATE_ADVERTISEMENT"
        ]
      }
    }
  },
  {
    "name": "TALENT_PAYMENT_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "GET_ADVERTISEMENT_CASH",
            "PAY_ADVERTISEMENT_CASH",
            "RECEIVE_TALENT_CASH",
            "PAY_TALENT_CASH"
        ]
      }
    }
  },
  {
    "name": "ADMIN_READ_ORGANIZER_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "ADMIN_BROWSE_ORGANIZER"
        ]
      }
    }
  },
  {
    "name": "ADMIN_RESOLVE_ORGANIZER_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "ADMIN_APPROVE_ORGANIZER",
            "ADMIN_UPDATE_ORGANIZER"
        ]
      }
    }
  },
  {
    "name": "ADMIN_ARCHIVE_ORGANIZER_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "ADMIN_DEACTIVE_ORGANIZER"
        ]
      }
    }
  },
  {
    "name": "ADMIN_READ_TALENT_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "ADMIN_BROWSE_TALENT",
            "ADMIN_BROWSE_ADVERTISEMENT"
        ]
      }
    }
  },
  {
    "name": "ADMIN_RESOLVE_TALENT_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "ADMIN_APPROVE_TALENT",
            "ADMIN_UPDATE_TALENT",
            "ADMIN_APPROVE_ADVERTISEMENT",
            "ADMIN_UPDATE_ADVERTISEMENT"
        ]
      }
    }
  },
  {
    "name": "ADMIN_ARCHIVE_TALENT_ACCESS",
    "composites": {
      "realm": null,
      "client": {
        "backend": [
            "ADMIN_DEACTIVE_TALENT",
            "ADMIN_DELETE_ADVERTISEMENT"
        ]
      }
    }
  }
]