{
  "username": "root",
  "enabled": true,
  "realmRoles": [
    "FULL_ADMIN",
    "VERIFIED_TALENT",
    "VERIFIED_ORGANIZER",
  ],
  "credentials": [
    {
      "type": "password",
      "value": "root"
    }
  ]
},
{
  "username": "readonly_admin",
  "enabled": true,
  "realmRoles": [
    "READONLY_ADMIN"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "readonly_admin"
    }
  ]
},
{
  "username": "organizer",
  "enabled": true,
  "realmRoles": [
    "VERIFIED_ORGANIZER"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "organizer"
    }
  ]
},
{
  "username": "guest_organizer",
  "enabled": true,
  "realmRoles": [
      "GUEST_ORGANIZER"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "guest_organizer"
    }
  ]
},
{
  "username": "guest_talent",
  "enabled": true,
  "realmRoles": [
    "GUEST_TALENT"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "guest_talent"
    }
  ]
},
{
  "username": "talent",
  "enabled": true,
  "realmRoles": [
      "VERIFIED_TALENT"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "talent"
    }
  ]
},