{
  "username": "root",
  "enabled": true,
  "realmRoles": [
    "ADMIN_READ_BOOKING_ACCESS",
    "ADMIN_RESOLVE_BOOKING_ACCESS",
    "ADMIN_ARCHIVE_ORGANIZER_ACCESS",
    "ADMIN_ARCHIVE_TALENT_ACCESS",
    "ADMIN_READ_ORGANIZER_ACCESS",
    "ADMIN_RESOLVE_TALENT_ACCESS",
    "ADMIN_READ_TALENT_ACCESS",
    "ADMIN_RESOLVE_ORGANIZER_ACCESS",
    "ORGANIZER_MODIFY_ACCESS",
    "ORGANIZER_WRITE_ACCESS",
    "ORGANIZER_READ_ACCESS",
    "ORGANIZER_PAYMENT_ACCESS",
    "TALENT_MODIFY_ACCESS",
    "TALENT_READ_ACCESS",
    "TALENT_WRITE_ACCESS",
    "TALENT_PAYMENT_ACCESS"
  ],
  "clientRoles": {
    "backend": [
        "ROOT"
    ]
  },
  "credentials": [
    {
      "type": "password",
      "value": "root"
    }
  ]
},
{
  "username": "office_admin",
  "enabled": true,
  "realmRoles": [
    "ADMIN_ARCHIVE_ORGANIZER_ACCESS",
    "ADMIN_ARCHIVE_TALENT_ACCESS",
    "ADMIN_READ_ORGANIZER_ACCESS",
    "ADMIN_RESOLVE_TALENT_ACCESS",
    "ADMIN_READ_TALENT_ACCESS",
    "ADMIN_RESOLVE_ORGANIZER_ACCESS"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "office_admin"
    }
  ]
},
{
  "username": "bd_admin",
  "enabled": true,
  "realmRoles": [
    "ADMIN_READ_BOOKING_ACCESS",
    "ADMIN_RESOLVE_BOOKING_ACCESS"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "bd_admin"
    }
  ]
},
{
  "username": "finance_admin",
  "enabled": true,
  "realmRoles": [
    "ADMIN_READ_BOOKING_ACCESS"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "finance_admin"
    }
  ]
},
{
  "username": "organizer",
  "enabled": true,
  "realmRoles": [
    "ORGANIZER_MODIFY_ACCESS",
    "ORGANIZER_WRITE_ACCESS",
    "ORGANIZER_READ_ACCESS",
    "ORGANIZER_PAYMENT_ACCESS"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "organizer"
    }
  ]
},
{
  "username": "guest_organizer",
  "enabled": true,
  "realmRoles": [
    "ORGANIZER_READ_ACCESS"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "guest_organizer"
    }
  ]
},
{
  "username": "guest_talent",
  "enabled": true,
  "realmRoles": [
    "TALENT_READ_ACCESS"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "guest_talent"
    }
  ]
},
{
  "username": "talent",
  "enabled": true,
  "realmRoles": [
    "TALENT_MODIFY_ACCESS",
    "TALENT_READ_ACCESS",
    "TALENT_WRITE_ACCESS",
    "TALENT_PAYMENT_ACCESS"
  ],
  "credentials": [
    {
      "type": "password",
      "value": "talent"
    }
  ]
},
{
  "username": "ssoadmin",
  "enabled": true,
  "clientRoles": {
    "realm-management": [
        "view-users",
        "manage-users"
    ]
  },
  "credentials": [
    {
      "type": "password",
      "value": "ssoadmin"
    }
  ]
}